//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 服务器端接收程序.GuangDaiService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.iotrust.com.cn", ConfigurationName="GuangDaiService.CorePlatformWebService")]
    public interface CorePlatformWebService {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        服务器端接收程序.GuangDaiService.getVersionResponse getVersion(服务器端接收程序.GuangDaiService.getVersion request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        服务器端接收程序.GuangDaiService.transmitTransparentlyResponse transmitTransparently(服务器端接收程序.GuangDaiService.transmitTransparently request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        服务器端接收程序.GuangDaiService.doConfigResponse doConfig(服务器端接收程序.GuangDaiService.doConfig request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iotrust.com.cn")]
    public partial class versionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iotrust.com.cn")]
    public partial class config : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool resultField;
        
        private int valueField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iotrust.com.cn")]
    public partial class transmitTransparentlyResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool resultField;
        
        private byte[] valueField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVersion", WrapperNamespace="http://www.iotrust.com.cn", IsWrapped=true)]
    public partial class getVersion {
        
        public getVersion() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getVersionResponse", WrapperNamespace="http://www.iotrust.com.cn", IsWrapped=true)]
    public partial class getVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.iotrust.com.cn", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public 服务器端接收程序.GuangDaiService.versionResponse @return;
        
        public getVersionResponse() {
        }
        
        public getVersionResponse(服务器端接收程序.GuangDaiService.versionResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transmitTransparently", WrapperNamespace="http://www.iotrust.com.cn", IsWrapped=true)]
    public partial class transmitTransparently {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.iotrust.com.cn", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wscId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.iotrust.com.cn", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int addr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.iotrust.com.cn", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hexCommand;
        
        public transmitTransparently() {
        }
        
        public transmitTransparently(string wscId, int addr, string hexCommand) {
            this.wscId = wscId;
            this.addr = addr;
            this.hexCommand = hexCommand;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transmitTransparentlyResponse", WrapperNamespace="http://www.iotrust.com.cn", IsWrapped=true)]
    public partial class transmitTransparentlyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.iotrust.com.cn", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public 服务器端接收程序.GuangDaiService.transmitTransparentlyResult @return;
        
        public transmitTransparentlyResponse() {
        }
        
        public transmitTransparentlyResponse(服务器端接收程序.GuangDaiService.transmitTransparentlyResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doConfig", WrapperNamespace="http://www.iotrust.com.cn", IsWrapped=true)]
    public partial class doConfig {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.iotrust.com.cn", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wscId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.iotrust.com.cn", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int index;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.iotrust.com.cn", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int function;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.iotrust.com.cn", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.iotrust.com.cn", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string remark;
        
        public doConfig() {
        }
        
        public doConfig(string wscId, int index, int function, int value, string remark) {
            this.wscId = wscId;
            this.index = index;
            this.function = function;
            this.value = value;
            this.remark = remark;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doConfigResponse", WrapperNamespace="http://www.iotrust.com.cn", IsWrapped=true)]
    public partial class doConfigResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.iotrust.com.cn", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public 服务器端接收程序.GuangDaiService.config @return;
        
        public doConfigResponse() {
        }
        
        public doConfigResponse(服务器端接收程序.GuangDaiService.config @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CorePlatformWebServiceChannel : 服务器端接收程序.GuangDaiService.CorePlatformWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CorePlatformWebServiceClient : System.ServiceModel.ClientBase<服务器端接收程序.GuangDaiService.CorePlatformWebService>, 服务器端接收程序.GuangDaiService.CorePlatformWebService {
        
        public CorePlatformWebServiceClient() {
        }
        
        public CorePlatformWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CorePlatformWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CorePlatformWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CorePlatformWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        服务器端接收程序.GuangDaiService.getVersionResponse 服务器端接收程序.GuangDaiService.CorePlatformWebService.getVersion(服务器端接收程序.GuangDaiService.getVersion request) {
            return base.Channel.getVersion(request);
        }
        
        public 服务器端接收程序.GuangDaiService.versionResponse getVersion() {
            服务器端接收程序.GuangDaiService.getVersion inValue = new 服务器端接收程序.GuangDaiService.getVersion();
            服务器端接收程序.GuangDaiService.getVersionResponse retVal = ((服务器端接收程序.GuangDaiService.CorePlatformWebService)(this)).getVersion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        服务器端接收程序.GuangDaiService.transmitTransparentlyResponse 服务器端接收程序.GuangDaiService.CorePlatformWebService.transmitTransparently(服务器端接收程序.GuangDaiService.transmitTransparently request) {
            return base.Channel.transmitTransparently(request);
        }
        
        public 服务器端接收程序.GuangDaiService.transmitTransparentlyResult transmitTransparently(string wscId, int addr, string hexCommand) {
            服务器端接收程序.GuangDaiService.transmitTransparently inValue = new 服务器端接收程序.GuangDaiService.transmitTransparently();
            inValue.wscId = wscId;
            inValue.addr = addr;
            inValue.hexCommand = hexCommand;
            服务器端接收程序.GuangDaiService.transmitTransparentlyResponse retVal = ((服务器端接收程序.GuangDaiService.CorePlatformWebService)(this)).transmitTransparently(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        服务器端接收程序.GuangDaiService.doConfigResponse 服务器端接收程序.GuangDaiService.CorePlatformWebService.doConfig(服务器端接收程序.GuangDaiService.doConfig request) {
            return base.Channel.doConfig(request);
        }
        
        public 服务器端接收程序.GuangDaiService.config doConfig(string wscId, int index, int function, int value, string remark) {
            服务器端接收程序.GuangDaiService.doConfig inValue = new 服务器端接收程序.GuangDaiService.doConfig();
            inValue.wscId = wscId;
            inValue.index = index;
            inValue.function = function;
            inValue.value = value;
            inValue.remark = remark;
            服务器端接收程序.GuangDaiService.doConfigResponse retVal = ((服务器端接收程序.GuangDaiService.CorePlatformWebService)(this)).doConfig(inValue);
            return retVal.@return;
        }
    }
}
