#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace 服务器端接收程序.SWS_DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SWS_DB")]
	public partial class SWS_DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertorg(org instance);
    partial void Updateorg(org instance);
    partial void Deleteorg(org instance);
    partial void Insertguangdai_station_link(guangdai_station_link instance);
    partial void Updateguangdai_station_link(guangdai_station_link instance);
    partial void Deleteguangdai_station_link(guangdai_station_link instance);
    #endregion
		
		public SWS_DBDataContext() : 
				base(global::服务器端接收程序.Properties.Settings.Default.SWS_DBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public SWS_DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SWS_DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SWS_DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SWS_DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<org> org
		{
			get
			{
				return this.GetTable<org>();
			}
		}
		
		public System.Data.Linq.Table<guangdai_station_link> guangdai_station_link
		{
			get
			{
				return this.GetTable<guangdai_station_link>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.org")]
	public partial class org : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _orgid;
		
		private string _name;
		
		private string _smallname;
		
		private string _address;
		
		private string _zip;
		
		private string _manager;
		
		private string _tel;
		
		private string _note;
		
		private string _highdept;
		
		private string _highmanager;
		
		private string _hightel;
		
		private string _dbip;
		
		private string _dbname;
		
		private string _webip;
		
		private string _videoip;
		
		private string _videotype;
		
		private string _position;
		
		private string _projectnum;
		
		private System.Nullable<int> _org_type;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnorgidChanging(string value);
    partial void OnorgidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnsmallnameChanging(string value);
    partial void OnsmallnameChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnzipChanging(string value);
    partial void OnzipChanged();
    partial void OnmanagerChanging(string value);
    partial void OnmanagerChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    partial void OnhighdeptChanging(string value);
    partial void OnhighdeptChanged();
    partial void OnhighmanagerChanging(string value);
    partial void OnhighmanagerChanged();
    partial void OnhightelChanging(string value);
    partial void OnhightelChanged();
    partial void OndbipChanging(string value);
    partial void OndbipChanged();
    partial void OndbnameChanging(string value);
    partial void OndbnameChanged();
    partial void OnwebipChanging(string value);
    partial void OnwebipChanged();
    partial void OnvideoipChanging(string value);
    partial void OnvideoipChanged();
    partial void OnvideotypeChanging(string value);
    partial void OnvideotypeChanged();
    partial void OnpositionChanging(string value);
    partial void OnpositionChanged();
    partial void OnprojectnumChanging(string value);
    partial void OnprojectnumChanged();
    partial void Onorg_typeChanging(System.Nullable<int> value);
    partial void Onorg_typeChanged();
    #endregion
		
		public org()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orgid", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string orgid
		{
			get
			{
				return this._orgid;
			}
			set
			{
				if ((this._orgid != value))
				{
					this.OnorgidChanging(value);
					this.SendPropertyChanging();
					this._orgid = value;
					this.SendPropertyChanged("orgid");
					this.OnorgidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(40)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smallname", DbType="NVarChar(20)")]
		public string smallname
		{
			get
			{
				return this._smallname;
			}
			set
			{
				if ((this._smallname != value))
				{
					this.OnsmallnameChanging(value);
					this.SendPropertyChanging();
					this._smallname = value;
					this.SendPropertyChanged("smallname");
					this.OnsmallnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(60)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip", DbType="VarChar(50)")]
		public string zip
		{
			get
			{
				return this._zip;
			}
			set
			{
				if ((this._zip != value))
				{
					this.OnzipChanging(value);
					this.SendPropertyChanging();
					this._zip = value;
					this.SendPropertyChanged("zip");
					this.OnzipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manager", DbType="NVarChar(8)")]
		public string manager
		{
			get
			{
				return this._manager;
			}
			set
			{
				if ((this._manager != value))
				{
					this.OnmanagerChanging(value);
					this.SendPropertyChanging();
					this._manager = value;
					this.SendPropertyChanged("manager");
					this.OnmanagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="VarChar(20)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="NVarChar(400)")]
		public string note
		{
			get
			{
				return this._note;
			}
			set
			{
				if ((this._note != value))
				{
					this.OnnoteChanging(value);
					this.SendPropertyChanging();
					this._note = value;
					this.SendPropertyChanged("note");
					this.OnnoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_highdept", DbType="NVarChar(40)")]
		public string highdept
		{
			get
			{
				return this._highdept;
			}
			set
			{
				if ((this._highdept != value))
				{
					this.OnhighdeptChanging(value);
					this.SendPropertyChanging();
					this._highdept = value;
					this.SendPropertyChanged("highdept");
					this.OnhighdeptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_highmanager", DbType="NVarChar(8)")]
		public string highmanager
		{
			get
			{
				return this._highmanager;
			}
			set
			{
				if ((this._highmanager != value))
				{
					this.OnhighmanagerChanging(value);
					this.SendPropertyChanging();
					this._highmanager = value;
					this.SendPropertyChanged("highmanager");
					this.OnhighmanagerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hightel", DbType="VarChar(20)")]
		public string hightel
		{
			get
			{
				return this._hightel;
			}
			set
			{
				if ((this._hightel != value))
				{
					this.OnhightelChanging(value);
					this.SendPropertyChanging();
					this._hightel = value;
					this.SendPropertyChanged("hightel");
					this.OnhightelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dbip", DbType="VarChar(15)")]
		public string dbip
		{
			get
			{
				return this._dbip;
			}
			set
			{
				if ((this._dbip != value))
				{
					this.OndbipChanging(value);
					this.SendPropertyChanging();
					this._dbip = value;
					this.SendPropertyChanged("dbip");
					this.OndbipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dbname", DbType="VarChar(20)")]
		public string dbname
		{
			get
			{
				return this._dbname;
			}
			set
			{
				if ((this._dbname != value))
				{
					this.OndbnameChanging(value);
					this.SendPropertyChanging();
					this._dbname = value;
					this.SendPropertyChanged("dbname");
					this.OndbnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_webip", DbType="VarChar(15)")]
		public string webip
		{
			get
			{
				return this._webip;
			}
			set
			{
				if ((this._webip != value))
				{
					this.OnwebipChanging(value);
					this.SendPropertyChanging();
					this._webip = value;
					this.SendPropertyChanged("webip");
					this.OnwebipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_videoip", DbType="VarChar(15)")]
		public string videoip
		{
			get
			{
				return this._videoip;
			}
			set
			{
				if ((this._videoip != value))
				{
					this.OnvideoipChanging(value);
					this.SendPropertyChanging();
					this._videoip = value;
					this.SendPropertyChanged("videoip");
					this.OnvideoipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_videotype", DbType="VarChar(15)")]
		public string videotype
		{
			get
			{
				return this._videotype;
			}
			set
			{
				if ((this._videotype != value))
				{
					this.OnvideotypeChanging(value);
					this.SendPropertyChanging();
					this._videotype = value;
					this.SendPropertyChanged("videotype");
					this.OnvideotypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="VarChar(50)")]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this.OnpositionChanging(value);
					this.SendPropertyChanging();
					this._position = value;
					this.SendPropertyChanged("position");
					this.OnpositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_projectnum", DbType="VarChar(5)")]
		public string projectnum
		{
			get
			{
				return this._projectnum;
			}
			set
			{
				if ((this._projectnum != value))
				{
					this.OnprojectnumChanging(value);
					this.SendPropertyChanging();
					this._projectnum = value;
					this.SendPropertyChanged("projectnum");
					this.OnprojectnumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_org_type", DbType="Int")]
		public System.Nullable<int> org_type
		{
			get
			{
				return this._org_type;
			}
			set
			{
				if ((this._org_type != value))
				{
					this.Onorg_typeChanging(value);
					this.SendPropertyChanging();
					this._org_type = value;
					this.SendPropertyChanged("org_type");
					this.Onorg_typeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.guangdai_station_link")]
	public partial class guangdai_station_link : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _wsid;
		
		private string _db_name;
		
		private System.Nullable<int> _station_id;
		
		private System.Nullable<int> _type;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnwsidChanging(string value);
    partial void OnwsidChanged();
    partial void Ondb_nameChanging(string value);
    partial void Ondb_nameChanged();
    partial void Onstation_idChanging(System.Nullable<int> value);
    partial void Onstation_idChanged();
    partial void OntypeChanging(System.Nullable<int> value);
    partial void OntypeChanged();
    #endregion
		
		public guangdai_station_link()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wsid", DbType="VarChar(50)")]
		public string wsid
		{
			get
			{
				return this._wsid;
			}
			set
			{
				if ((this._wsid != value))
				{
					this.OnwsidChanging(value);
					this.SendPropertyChanging();
					this._wsid = value;
					this.SendPropertyChanged("wsid");
					this.OnwsidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_db_name", DbType="VarChar(50)")]
		public string db_name
		{
			get
			{
				return this._db_name;
			}
			set
			{
				if ((this._db_name != value))
				{
					this.Ondb_nameChanging(value);
					this.SendPropertyChanging();
					this._db_name = value;
					this.SendPropertyChanged("db_name");
					this.Ondb_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_station_id", DbType="Int")]
		public System.Nullable<int> station_id
		{
			get
			{
				return this._station_id;
			}
			set
			{
				if ((this._station_id != value))
				{
					this.Onstation_idChanging(value);
					this.SendPropertyChanging();
					this._station_id = value;
					this.SendPropertyChanged("station_id");
					this.Onstation_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
